[package]
cjc-version = "1.0.5"
name = "cangjiegui_component_gallery"
version = "0.1.0"
output-type = "executable"
description = "Desktop preview gallery for CangjieGUI common components."

[dependencies]
cui = { path = "../.." }
cangjiegui_gallery_components = { path = "../../packages/gallery-components" }
